version: '2'
services:
  web:
    image: buig/sf-php8.0-apache
    container_name: carverse
    volumes:
      - .:/code
      - ./provisioning/sites-enabled:/etc/apache2/sites-enabled
    env_file:
      - .env.webapp
    ports:
      - 8082:80
    networks:
      - carverse-shared
    tty: true

networks:
  carverse-shared:
    external: true
